- id: 200
  key: satoshi
  currency: btc
  sort_order: 1
  min_confirm: 1
  max_confirm: 3
- id: 400
  key: bank
  currency: cny
  sort_order: 2
  bank_accounts:
    -
      bank: 'Your Bank Name'
      branch: 'Your Bank Branch'
      holder: 'Your Account Holder'
      account: 'Your Account Number'
- id: 600
  key: ether
  currency: eth
  min_confirm: 1
  max_confirm: 6
- id: 800
  key: bank
  currency: inr
  sort_order: 3
  bank_accounts:
    -
      bank: 'Your Bank Name'
      branch: 'Your Bank Branch'
      holder: 'Your Account Holder'
      account: 'Your Account Number'
- id: 900
  key: bank
  currency: usd
  sort_order: 4
  bank_accounts:
    -
      bank: 'Your Bank Name'
      branch: 'Your Bank Branch'
      holder: 'Your Account Holder'
      account: 'Your Account Number'
- id: 1000
  key: bank
  currency: aud
  sort_order: 5
  bank_accounts:
    -
      bank: 'Your Bank Name'
      branch: 'Your Bank Branch'
      holder: 'Your Account Holder'
      account: 'Your Account Number'
- id: 1100
  key: ripple
  currency: xrp
  sort_order: 1
  min_confirm: 1
  max_confirm: 3

- id: 700
  key: litecoin
  currency: ltc
  min_confirm: 1
  max_confirm: 6